name: "CI: website"

on:
  pull_request:
    branches:
      - main

jobs:
  # lint-typecheck-test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.14]
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: Get yarn cache directory path
  #       id: yarn-cache-dir-path
  #       run: echo "::set-output name=dir::$(yarn cache dir)"

  #     - uses: actions/cache@v1
  #       id: yarn-cache
  #       with:
  #         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
  #         key: yarn-cache-${{ hashFiles('./yarn.lock') }}
  #         restore-keys: |
  #           yarn-cache-${{ hashFiles('./yarn.lock') }}
  #     - name: Install dependencies
  #       run: |
  #         yarn install --immutable
  #     - name: Run typecheck
  #       run: |
  #         yarn run typecheck
  #     - name: Run linter
  #       run: |
  #         yarn run lint --max-warnings 0

  build:
    runs-on: ubuntu-latest
    environment:
      name: test
      url: http://github.com
    strategy:
      matrix:
        node-version: [16.14]
    steps:
      - name: Env Variables
        run: |
          echo $GITHUB_ACTOR
      # - uses: actions/checkout@v2

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}

      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "::set-output name=dir::$(yarn cache dir)"

      # - name: Install Netlify CLI
      #   run: |
      #     yarn global add netlify-cli

      # - uses: actions/cache@v1
      #   id: yarn-cache
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: yarn-cache-${{ hashFiles('./yarn.lock') }}
      #     restore-keys: |
      #       yarn-cache-${{ hashFiles('./yarn.lock') }}

      # - name: Install dependencies
      #   run: |
      #     yarn install --immutable
      # - name: Run typecheck
      #   run: |
      #     yarn run typecheck
      # - name: Run linter
      #   run: |
      #     yarn run lint --max-warnings 0
      - name: Build & Deploy Website
        run: env
        # run: |
        #   yarn deploy
        # uses:
        #   NETLIFY_AUTH_TOKEN: ${{ env.NETLIFY_AUTH_TOKEN }}
